### ISSUE TITLE
No way to make initial state final

### ISSUE THREAD

**Issue by kevinzying** [mrkev/fsmgen#1]
As far as I can tell. 

final initial state q0 =
  | stay -> q0
  | move -> q1
  | jump -> q2

state q1 =
  | back -> q0
  | stay -> q1
  | move -> q2

final state q2 =
  | stay -> q2
  | restart -> q0

gives error message

Expected "state" but "i" found.

**Comment by mrkev** [comment]
Added support for this in https://github.com/mrkev/fsmgen/commit/6e3dfe59b20b1f4ba5e4e273c565931557a39743 (:
